### ISSUE TITLE
afterSave and afterCreate callbacks are not firing on nested objects

### ISSUE THREAD

**Issue by chapmandu** [cfwheels/cfwheels#525] opened 2015-07-17 08:52 UTC
It would appear that afterSave and afterCreate callbacks are not firing on nested objects when obj.save() is called. 
It seems to have broken between 1.1.8 and 1.3.4

**Comment by perdjurner** [comment] 2015-07-17 08:58
Do you think you can find out exactly which version broke it?

**Comment by chapmandu** [comment] 2015-07-17 09:37
Yes, I can.. I'll post as soon asap.

**Comment by lmah** [comment] 2015-07-18 01:54
Hi Per,

This was working on version 1.3.1, and not working onwwards.

**Comment by chrisdpeters** [comment] 2015-07-29 18:01
We're upgrading our biggest CFWheels app, and I can verify that `beforeCreate` is also not running.

I'll dig around and see if I can find the offending code.

**Comment by chrisdpeters** [comment] 2015-07-29 21:42
This is a regression introduced by e446e11046e56e81210741ac4d11bed6433fe260.

I see what @perdjurner was trying to accomplish there. The code is manually validating associated models with the call to `$validateAssociations`. But then it turns off callbacks when it later calls `$saveAssocations`, which is causing this bug on all of the other callbacks that are not related to validations.

I am going to commit failing tests that uncover this bug. I'm not quite sure how to solve. It seems like `save` needs to also accept a list of callbacks that should be run instead of just a `true`/`false` value. But perhaps Per has a better idea...

If you change it to `callbacks=true` on [line 93 of `wheels/model/create.cfm`](https://github.com/cfwheels/cfwheels/blob/bb3e1b0fcf4138fb76ac23218dd88e43fb769816/wheels/model/create.cfm#L93), my tests pass, but the 1 related to #284 in another part of the core fails. If you leave it as `callbacks=false`, my tests fail, but the other one passes.

**Comment by perdjurner** [comment] 2015-07-29 21:45
Good find, please commit the failing tests but comment them out.

**Comment by chrisdpeters** [comment] 2015-07-29 21:47
@perdjurner I committed in branch issue_525, but they are not commented out. Hope that is OK. Shouldn't disrupt master.

**Comment by perdjurner** [comment] 2015-07-29 21:47
Ok, yeah, that's fine.

Thanks.

**Comment by perdjurner** [comment] 2015-08-09 20:37
@chrisdpeters Check my commit to your branch please.

Do you think that fixes it?

Here's the reasoning regarding those minor changes I made:

$validateAssociations(callbacks=false)
Callbacks not needed here since we'll do those when saving below anyway.

$saveAssociations(argumentCollection=arguments, validate=false)
Validate not needed since we did that above anyway.

**Comment by chrisdpeters** [comment] 2015-08-10 14:33
@perdjurner Unfortunately, that approach doesn't work. What I think we need to do is change the `callbacks` argument to accept a boolean _or_ a list of callbacks that it needs to run.

We basically have a situation where we need to run validation callbacks along with `$validateAssociations` and then the rest of the callbacks later with `$saveAssociations`. I cannot think of another way around it. What do you think?

As you were probably alerted, I just committed a failing test. Keep in mind that it will corrupt the test data because it fails by throwing an exception, so you need to reload test data after each run.

**Comment by chrisdpeters** [comment] 2015-08-10 14:35
@perdjurner When I mention the `callbacks` argument, I mean the `callbacks` argument for `save`.

**Comment by chrisdpeters** [comment] 2015-08-11 16:07
@perdjurner Per our discussion, I've committed tests that fail when the parent record has failed validation and the child(ren)'s `beforeValidation` callbacks do not fire.

To everyone following this issue, we're getting closer!

**Comment by chrisdpeters** [comment] 2015-08-11 17:56
@chapmandu I think we have this resolved. Can you swap in the wheels folder from the issue_525 branch and verify that it fixes your issue?

**Comment by chapmandu** [comment] 2015-08-13 05:52
Thanks @chrisdpeters & @perdjurner 

@lmah let's test this..

**Comment by lmah** [comment] 2015-08-20 23:46
Hi @chrisdpeters  & @perdjurner,

I have tested this, and can verify that it is now fixed. Thanks guys!

**Comment by chrisdpeters** [comment] 2015-08-21 01:20
@lmah :thumbsup:

Thanks for helping test this.

**Closed** 2015-08-21 01:28 UTC
Labels: bug
