### ISSUE TITLE
findAll(returnAs="struct") does not execute afterFind hook

### ISSUE THREAD

**Issue by geirman** [cfwheels/cfwheels#948] opened 2019-05-10 15:54 UTC
While preparing the demo for issue #945, I noticed this unexpected result. It doesn't appear that the `afterFind` hook is being ran when the returnAs is "stuct". 

## Code
In my `Quote.cfc` model I have this hook setup...

```

afterFind('handleAfterFind');

function handleAfterFind() {
	var hasId = structKeyExists(arguments, 'id');

	if(hasId) {
		arguments.id = obfuscateParam(arguments.id);
	}

	return arguments;
}
```

<img width="907" alt="2019-05-10_0851 | CFW as Query" src="https://user-images.githubusercontent.com/1640318/57540220-0fdfd680-7301-11e9-8290-86dc32bc520a.png">
<img width="1083" alt="2019-05-10_0852 | CFW as Struct" src="https://user-images.githubusercontent.com/1640318/57540222-0fdfd680-7301-11e9-9215-553e5e45af19.png">

**Comment by chapmandu** [comment] 2019-05-15 11:16
Duplicate of https://github.com/cfwheels/cfwheels/issues/605 (but nicely documented)

**Closed by chapmandu** 2019-05-15 11:16 UTC
