### ISSUE TITLE
Routing issue [controller]/index calling show action

### ISSUE THREAD

**Issue by kmd1970** [cfwheels/cfwheels#823] opened 2017-10-19 18:35 UTC
My routes are defined as shown below in v2.0:

```js
 mapper()
// The "wildcard" call below enables automatic mapping of "controller/action" type routes.
// This way you don't need to explicitly add a route every time you create a new action in a controller.

 .resources("users")
 .wildcard()	

// The root route below is the one that will be called on your application's home page (e.g. http://127.0.0.1/).
// You can, for example, change "wheels##wheels" to "home##index" to call the "index" action on the "home" controller instead.
.root(to="home##index", method="get")
 .end();
```

GET /users/[key] (**Calls the Show action, as expected**)
GET /users/ (**Calls Index action, as expected**)
GET /users/index (**Calls the Show action??, not expected**)

Now, if I move the `.wildcard()` above  `.resources("users")` it fixes 
GET /users/index (**Calls the Index action, as expected**)
but breaks
GET /users/[key] (**Wheels.ViewNotFound [key].cfm**)

**Comment by neokoenig** [comment] 2017-10-19 21:49
I think what the issue is that `users/index` in the `resources` route is treating the `index` part of the path as a `[key]` - so technically, I think it's actually matching correctly. Of course, `index` isn't an integer, so `show` would probably get confused if you had no checks in that function by using `verifies()`.

`Wildcard()` is a throw back to simple `controller/action` routes (we did actually consider completely removing it actually): there's no `[key]` matching (by design) and it will only match `GET` (although I might be wrong on that). So when you pass `users/1` into the `wildcard()` route, it will look for `1.cfm` in the `/users/` folder.

The sum of it is that `resources()` has no implicit mapping for `users/index` - just use `users`. Get rid of the `wildcard()` - it will make more sense in the longterm

**Comment by neokoenig** [comment] 2017-10-24 12:12
Closing, feel free to re-open

**Closed by neokoenig** 2017-10-24 12:12 UTC
